version: '2.1'
services:
  app:
    container_name: my-resume2-app
    image: colus3/my-resume2-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    environment:
      - TZ=Asia/Seoul
    command: npm run dev
